version: "3.1"

services:
  mysql:
    container_name: "protube-2-mysql"
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: "thisisareallystrongpassword123"
      MYSQL_DATABASE: "${DATABASE_DB}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${DATABASE_PORT}:3306"
  
  phpmyadmin:
    container_name: 'protube-2-pma'
    image: phpmyadmin
    ports:
        - '8079:80'
    environment:
        - 'PMA_HOST=mysql'
        - 'PMA_USER=${DATABASE_USER}'
        - 'PMA_PASSWORD=${DATABASE_PASSWORD}'
        - 'PMA_PORT=3306'