name: Lint Client

on:
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  linting-server:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Get Node version
        run: echo "NODE_VERSION=$(<.nvmrc)" >> $GITHUB_ENV

      - name: Set Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: cd client && npm install

      - name: Run linters for server
        uses: wearerequired/lint-action@v2
        with:
          check_name: ${linter}-client
          eslint: true
          eslint_dir: client/
          prettier: true
          prettier_dir: client/